version: 1.0.{build}
branches:
  only:
  - master
  publish_nuget: true
skip_tags: true
image: Visual Studio 2019
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: detailed
deploy:
- provider: NuGet
  api_key:
    secure: IbdzAhO9Z8bkoyx3plT3eie0Qmw02ItpPBr1TyUFqNdX8bnQR4F+q7VcoluMZ+Np
  skip_symbols: false
  on:
    branch: master